version: '3.2'

services:
  frontend:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imnext-js
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: imdockgroup
