version: '3.5'

services:
  server:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: imdockgroup
