version: '3.5'
services:
  server:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c 'yarn --production=false && yarn clean && yarn build-app && yarn serve'
    ports:
      - '3000:3000'
      - '5000:5000'

networks:
  default:
    external:
      name: imdockgroup
